name: Tests and lint
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linter
        run: |
          poetry run flake8 gendiff 
      - name: Test
        run: |
          poetry run pytest
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 04d27dfcd9bc0a1f3f0382aa1675175af47ffa4fce206e91372829061097f348
        with:
          coverageCommand: poetry run pytest --cov=gendiff --cov-report xml
          debug: true


